
- name: download enterprise gateway and kernel images
  shell: |
    docker pull elyra/kubernetes-enterprise-gateway:dev
    docker pull elyra/kubernetes-kernel-py:dev
    docker pull elyra/kubernetes-kernel-tf-py:dev
    docker pull elyra/kubernetes-kernel-r:dev
    docker pull elyra/kubernetes-kernel-scala:dev

- name: Deploy and Configure ACL for Jupyter Enterprise Gatewtay
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/jupyter-incubator/enterprise_gateway/{{ jupyter_enterprise_gateway.version }}/etc/kubernetes/enterprise-gateway.yaml
  when: inventory_hostname in groups['master']
