
#- pause:
#    minutes: 1

#https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/#requirements
- name: Install Calico Network
  shell: >
    kubectl apply -f https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml

- name: Dashboard security manifest
  template:
    src: dashboard-insecure.yaml.j2
    dest: "{{ install_temp_dir }}/dashboard-insecure.yaml"
    mode: 0644

- name: Install Dashboard
  shell: |
     kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
     kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f {{ install_temp_dir }}/dashboard-insecure.yaml

- name: Helm/Tiller access manifest
  template:
    src: tiller-access.yaml.j2
    dest: "{{ install_temp_dir }}/tiller-access.yaml.yaml"
    mode: 0644

- name: Install Helm
  shell: |
    wget https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-amd64.tar.gz
    mkdir /opt/helm
    tar -xvf helm-v2.9.1-linux-amd64.tar.gz --strip 1 --directory /opt/helm
    chmod u+x /opt/helm/helm
    ln -s /opt/helm/helm /usr/local/bin/helm
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f {{ install_temp_dir }}/tiller-access.yaml
    /usr/local/bin/helm init --service-account tiller

