
#https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/#requirements
- name: Install Calico Network
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/etcd.yaml
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/rbac.yaml
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/calico.yaml

#https://kubernetes.github.io/ingress-nginx/deploy/
- name: Add Traefik Ingress deployment descriptor
  template:
    src: traefik-ingress.yaml.j2
    dest: "{{ install_temp_dir }}/traefik-ingress.yaml"
    mode: 0644

- name: Install Traefik Ingress Controller
  shell: |
    kubectl apply -f {{ install_temp_dir }}/traefik-ingress.yaml

#https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
- name: Dashboard security manifest
  template:
    src: dashboard-rbac.yaml.j2
    dest: "{{ install_temp_dir }}/dashboard-rbac.yaml"
    mode: 0644

- name: Install Dashboard
  shell: |
     kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
#     kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f {{ install_temp_dir }}/dashboard-rbac.yaml

- name: Helm/Tiller access manifest
  template:
    src: tiller-access.yaml.j2
    dest: "{{ install_temp_dir }}/tiller-access.yaml"
    mode: 0644

- name: Install Helm
  shell: |
    wget https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-amd64.tar.gz
    mkdir /opt/helm
    tar -xvf helm-v2.9.1-linux-amd64.tar.gz --strip 1 --directory /opt/helm
    chmod u+x /opt/helm/helm
    ln -s /opt/helm/helm /usr/local/bin/helm
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f {{ install_temp_dir }}/tiller-access.yaml
    /usr/local/bin/helm init --service-account tiller
