
- name: set spark installation path fact
  set_fact: spark_installation_dir=spark-{{ spark.version }}-bin-with-hadoop-{{ spark.hadoop_version }}

- name: set spark archive fact
  set_fact: spark_archive=spark-{{ spark.version }}-bin-with-hadoop-{{ spark.hadoop_version }}.tgz

- name: set spark download location fact
  set_fact: spark_download={{ spark.download_location }}/{{ spark_archive }}

- debug:
     msg: "Downloading Spark from: {{ spark_download }}"

- name: download spark
  get_url: url="{{ spark_download }}" dest="{{ install_temp_dir }}/{{ spark_archive }}"

- name: create install directory
  file:
    path: "{{ install_dir }}/{{ spark_installation_dir }}"
    state: directory

- name: unarchive to the install directory
  shell: "tar --warning=no-unknown-keyword -zxf {{ install_temp_dir }}/{{ spark_archive }} --strip 1 --directory {{ install_dir }}/{{ spark_installation_dir }}"

# Environment setup.
- name: add spark profile to startup
  template:
    src: spark-env.sh.j2
    dest: /etc/profile.d/spark-env.sh
    mode: 0644
