- name: install commonly used os dependencies
  shell:
     yum install -y unzip bzip2 rsync

- name: upgrade all packages
  shell:
     yum update -y

- name: clean yum repository
  shell: "yum clean all"
